# Generated by Django 5.2.8 on 2025-11-23 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalItem',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=200)),
                ('cost_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_booked', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.IntegerField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CrewMember',
            fields=[
                ('crew_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flight_no', models.IntegerField(primary_key=True, serialize=False)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('schedule_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('passenger_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='BookingItem',
            fields=[
                ('booking_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('subtotal_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.additionalitem')),
            ],
        ),
        migrations.CreateModel(
            name='CrewAssignment',
            fields=[
                ('crew_assignment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('assignment_date', models.DateField()),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.crewmember')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flight')),
            ],
        ),
        migrations.CreateModel(
            name='FlightRoute',
            fields=[
                ('route_id', models.IntegerField(primary_key=True, serialize=False)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrivals', to='core.city')),
                ('origin_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='core.city')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flightroute'),
        ),
        migrations.AddField(
            model_name='flight',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flightschedule'),
        ),
        migrations.CreateModel(
            name='ItineraryItem',
            fields=[
                ('itinerary_item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.booking')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.flight')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.passenger'),
        ),
    ]
